repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-format
        files: ^(src|tests|scripts)/
      - id: ruff-check
        files: ^(src|tests|scripts)/
        args: [--fix]
