"""Canonical field schema for pymodes Decoded results.

`_FULL_SCHEMA` declares every key that any pyModeS decoder may emit.
It serves two purposes:

1. The `full_dict=True` mode populates missing keys with explicit
   `None` so callers get a uniform shape regardless of message type.
2. A drift-detection test (`tests/test_schema.py`) walks the test
   message corpus and asserts no decoder ever emits a key not
   declared here.

The schema was generated by surveying every decoder module's dict
literals and `result[...] = ...` subscript assignments. The type
annotations on the right side are documentation only -- runtime
ignores them. Use bare `type` for "always present in this context"
and string-form unions like `"int | None"` for optional.

When you add a new BDS register or extend an existing decoder with
a new key, add the key here too. The drift-detection test catches
omissions.
"""

_FULL_SCHEMA: dict[str, type | str] = {
    # Always present (set by Message.decode for any DF)
    "df": int,
    "icao": str,
    # Set by Message.decode for DF17/18/20/21
    "crc_valid": "bool | None",
    # Set by Message.decode for DF20/21 only
    "icao_verified": "bool | None",
    # Set by Message._resolve_position when CPR is resolved
    "latitude": "float | None",
    "longitude": "float | None",
    # Error envelope (set by PipeDecoder / batch decode for corrupt input)
    "error": "str | None",
    "raw_msg": "str | None",
    # ADS-B common (DF17/18)
    "typecode": "int | None",
    "bds": "str | None",
    "bds_candidates": "list[str] | None",
    # Surveillance reply header (DF4/5/20/21)
    "altitude": "int | None",
    "squawk": "str | None",
    "flight_status": "int | None",
    "flight_status_text": "str | None",
    "downlink_request": "int | None",
    "utility_message": "int | None",
    # All-call reply (DF11)
    "capability": "int | None",
    "capability_text": "str | None",
    # ACAS (DF0/16)
    "vertical_status": "str | None",
    "sensitivity_level": "int | None",
    "reply_information": "int | None",
    "cross_link_capability": "int | None",
    "mv": "str | None",
    # BDS 0,5 / 0,6 raw CPR
    "cpr_format": "int | None",
    "cpr_lat": "int | None",
    "cpr_lon": "int | None",
    "surveillance_status": "int | None",
    "nic_b": "int | None",
    "nuc_p": "int | None",
    # BDS 0,6 surface
    "movement": "int | None",
    "track_status": "int | None",
    # BDS 0,8 identification
    "callsign": "str | None",
    "category": "int | None",
    "wake_vortex": "str | None",
    # BDS 0,9 velocity (also reused for surface BDS 0,6)
    "subtype": "int | None",
    "groundspeed": "int | None",
    "track": "float | None",
    "heading": "float | None",
    "airspeed": "int | None",
    "airspeed_type": "str | None",
    "vertical_rate": "int | None",
    "vr_source": "str | None",
    "geo_minus_baro": "int | None",
    "nac_v": "int | None",
    # BDS 1,0 data link capability
    "config": "int | None",
    "overlay_command_capability": "bool | None",
    "acas_operational": "bool | None",
    "mode_s_subnetwork_version": "int | None",
    "transponder_level5": "bool | None",
    "uplink_elm_throughput": "int | None",
    "downlink_elm_throughput": "int | None",
    "aircraft_identification_capability": "bool | None",
    "squitter_capability": "bool | None",
    "surveillance_identifier_code": "bool | None",
    "common_usage_gicb_capability": "bool | None",
    "mode_s_specific_services": "bool | None",
    "acas_hybrid_surveillance": "bool | None",
    "acas_rtca_version": "int | None",
    "acas_resolution_advisory": "bool | None",
    "dte_status": "int | None",
    # BDS 1,7 GICB capability
    "supported_bds": "list[str] | None",
    # BDS 3,0 ACAS RA broadcast
    "threat_type_indicator": "int | None",
    "issued_ra": "bool | None",
    "corrective": "bool | None",
    "downward_sense": "bool | None",
    "increased_rate": "bool | None",
    "sense_reversal": "bool | None",
    "altitude_crossing": "bool | None",
    "positive": "bool | None",
    "no_above": "bool | None",
    "no_below": "bool | None",
    "no_left": "bool | None",
    "no_right": "bool | None",
    "ra_terminated": "bool | None",
    "multiple_threat": "bool | None",
    "threat_icao": "str | None",
    "threat_altitude": "int | None",
    "threat_range": "float | None",
    "threat_bearing": "int | None",
    # BDS 4,0 selected vertical intention
    "selected_altitude_mcp": "int | None",
    "selected_altitude_fms": "int | None",
    "baro_pressure_setting": "float | None",
    "vnav_mode": "bool | None",
    "altitude_hold_mode": "bool | None",
    "approach_mode": "bool | None",
    "target_altitude_source": "str | None",
    # BDS 4,4 met routine
    "wind_speed": "int | None",
    "wind_direction": "float | None",
    "static_air_temperature": "float | None",
    "static_pressure": "int | None",
    "humidity": "float | None",
    "turbulence": "int | None",
    "figure_of_merit": "int | None",
    # BDS 4,5 met hazard
    "wind_shear": "int | None",
    "microburst": "int | None",
    "icing": "int | None",
    "radio_height": "int | None",
    # BDS 5,0 track and turn
    "roll": "float | None",
    "true_track": "float | None",
    "true_airspeed": "int | None",
    "track_rate": "float | None",
    # BDS 6,0 heading and speed
    "magnetic_heading": "float | None",
    "indicated_airspeed": "int | None",
    "mach": "float | None",
    "baro_vertical_rate": "int | None",
    "inertial_vertical_rate": "int | None",
    # BDS 6,1 aircraft status
    "emergency_state": "int | None",
    # BDS 6,2 target state and status
    "selected_altitude": "int | None",
    "selected_altitude_source": "str | None",
    "selected_heading": "float | None",
    "autopilot": "bool | None",
    "lnav_mode": "bool | None",
    "tcas_operational": "bool | None",
    # BDS 6,5 operational status
    "version": "int | None",
    "capability_class": "int | None",
    "operational_mode": "int | None",
    "nic_supplement_a": "int | None",
    "nac_p": "int | None",
    "sil": "int | None",
    "sil_supplement": "int | None",
    "nic_baro": "int | None",
    "hrd": "str | None",
}
